# Generated by Django 5.1.6 on 2025-03-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_workspace_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
